In [53]:
import pandas as pd
from pyspark.sql.functions import column

In [54]:
df = pd.read_csv('../../data/raw_data/original_dataset_schema.csv')

In [55]:
df.describe()

,geschlecht,alter,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,...,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,-8.035448,-2.365672,-8.333955,-7.283582,3.072761,2.248134,2.085821,0.445896,0.037313,0.365672,...,-5.197761,-13.944030,-9.207090,-10.399254,-8.268657,-12.490672,-13.376866,-9.602612,-11.904851,-7.559701
std,29.207678,32.815267,30.142751,30.126987,1.019586,4.417890,7.608659,9.674944,11.416929,13.730540,...,29.127597,36.712531,33.116504,34.388722,32.261760,35.477410,36.434447,32.377226,34.900664,31.282616
min,-99.000000,-99.000000,-99.000000,-99.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,1.000000,6.000000,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,...,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,1.000000,8.000000,1.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,2.000000,...,4.000000,1.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000
75%,2.000000,10.000000,1.000000,3.000000,4.000000,3.000000,3.000000,2.000000,2.000000,3.000000,...,5.000000,2.000000,4.000000,4.000000,4.000000,2.250000,3.000000,3.000000,2.000000,4.000000
max,3.000000,15.000000,17.000000,9.000000,5.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [56]:
# Schritt 1: -99 in eigene Kategorie umcodieren (z. B. 4 oder 'unbekannt')
df['geschlecht'] = df['geschlecht'].replace(-99, 4)

# Optional: Als Kategorie umwandeln
df['geschlecht'] = df['geschlecht'].map({
    1: 'maennlich',
    2: 'weiblich',
    3: 'divers',
    4: 'unbekannt'
})

In [57]:
df.describe()

,alter,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,situation_gastro,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,...,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,-2.365672,-8.333955,-7.283582,3.072761,2.248134,2.085821,0.445896,0.037313,0.365672,-0.921642,...,-5.197761,-13.944030,-9.207090,-10.399254,-8.268657,-12.490672,-13.376866,-9.602612,-11.904851,-7.559701
std,32.815267,30.142751,30.126987,1.019586,4.417890,7.608659,9.674944,11.416929,13.730540,18.309729,...,29.127597,36.712531,33.116504,34.388722,32.261760,35.477410,36.434447,32.377226,34.900664,31.282616
min,-99.000000,-99.000000,-99.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,6.000000,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,...,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,8.000000,1.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,2.000000,3.000000,...,4.000000,1.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000
75%,10.000000,1.000000,3.000000,4.000000,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,...,5.000000,2.000000,4.000000,4.000000,4.000000,2.250000,3.000000,3.000000,2.000000,4.000000
max,15.000000,17.000000,9.000000,5.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [58]:
df['alter'] = df['alter'].replace(-99, 16)

In [59]:
df.describe()

,alter,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,situation_gastro,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,...,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,9.434701,-8.333955,-7.283582,3.072761,2.248134,2.085821,0.445896,0.037313,0.365672,-0.921642,...,-5.197761,-13.944030,-9.207090,-10.399254,-8.268657,-12.490672,-13.376866,-9.602612,-11.904851,-7.559701
std,3.465104,30.142751,30.126987,1.019586,4.417890,7.608659,9.674944,11.416929,13.730540,18.309729,...,29.127597,36.712531,33.116504,34.388722,32.261760,35.477410,36.434447,32.377226,34.900664,31.282616
min,2.000000,-99.000000,-99.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,7.000000,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,...,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,9.000000,1.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,2.000000,3.000000,...,4.000000,1.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000
75%,11.000000,1.000000,3.000000,4.000000,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,...,5.000000,2.000000,4.000000,4.000000,4.000000,2.250000,3.000000,3.000000,2.000000,4.000000
max,16.000000,17.000000,9.000000,5.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [60]:
mapping = {
    1: "nach 2008",
    2: "2008",
    3: "2007",
    4: "2006",
    5: "2005",
    6: "2004",
    7: "2003",
    8: "2002",
    9: "2001",
    10: "2000",
    11: "1999",
    12: "1998",
    13: "1997",
    14: "1996",
    15: "1995",
    16: "keine Angabe"
}

df['alter'] = df['alter'].map(mapping)

In [61]:
df.describe()
df['alter'].value_counts()

2000            77
2003            70
2002            62
keine Angabe    55
2004            52
1999            45
2001            42
2005            30
1998            30
1996            18
2006            16
1997            14
1995            13
2007             9
2008             3
Name: alter, dtype: int64

In [62]:
df['alter'].unique()

array(['2004', '2002', 'keine Angabe', '2005', '1999', '2003', '2000',
       '2006', '1996', '1995', '2001', '1997', '1998', '2007', '2008'],
      dtype=object)

In [63]:
df.describe()

,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,situation_gastro,situation_urlaub,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,...,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,-8.333955,-7.283582,3.072761,2.248134,2.085821,0.445896,0.037313,0.365672,-0.921642,-1.402985,...,-5.197761,-13.944030,-9.207090,-10.399254,-8.268657,-12.490672,-13.376866,-9.602612,-11.904851,-7.559701
std,30.142751,30.126987,1.019586,4.417890,7.608659,9.674944,11.416929,13.730540,18.309729,18.740478,...,29.127597,36.712531,33.116504,34.388722,32.261760,35.477410,36.434447,32.377226,34.900664,31.282616
min,-99.000000,-99.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,2.000000,...,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,1.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,2.000000,3.000000,2.000000,...,4.000000,1.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000
75%,1.000000,3.000000,4.000000,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,3.000000,...,5.000000,2.000000,4.000000,4.000000,4.000000,2.250000,3.000000,3.000000,2.000000,4.000000
max,17.000000,9.000000,5.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [64]:
df['bundesland'] = df['bundesland'].replace(-99, 18)

In [65]:
mapping = {
    1: "Baden-Württemberg",
    2: "Bayern",
    3: "Berlin",
    4: "Brandenburg",
    5: "Bremen",
    6: "Hamburg",
    7: "Hessen",
    8: "Mecklenburg-Vorpommern",
    9: "Niedersachsen",
    10: "Nordrhein-Westfalen",
    11: "Rheinland-Pfalz",
    12: "Saarland",
    13: "Sachsen",
    14: "Sachsen-Anhalt",
    15: "Schleswig-Holstein",
    16: "Thüringen",
    17: "nicht in Deutschland",
    18: "keine Angabe"
}

df['bundesland'] = df['bundesland'].map(mapping)

In [66]:
df['bundesland'].value_counts()

Baden-Württemberg       418
keine Angabe             53
Bayern                   36
Nordrhein-Westfalen       9
nicht in Deutschland      3
Hessen                    3
Sachsen                   3
Rheinland-Pfalz           3
Bremen                    2
Berlin                    2
Niedersachsen             2
Hamburg                   1
Thüringen                 1
Name: bundesland, dtype: int64

In [67]:
df.describe()

,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,situation_gastro,situation_urlaub,involvement_interesse,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,...,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,-7.283582,3.072761,2.248134,2.085821,0.445896,0.037313,0.365672,-0.921642,-1.402985,-0.080224,...,-5.197761,-13.944030,-9.207090,-10.399254,-8.268657,-12.490672,-13.376866,-9.602612,-11.904851,-7.559701
std,30.126987,1.019586,4.417890,7.608659,9.674944,11.416929,13.730540,18.309729,18.740478,17.414118,...,29.127597,36.712531,33.116504,34.388722,32.261760,35.477410,36.434447,32.377226,34.900664,31.282616
min,-99.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,...,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,...,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,2.000000,3.000000,2.000000,3.000000,...,4.000000,1.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000
75%,3.000000,4.000000,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,3.000000,4.000000,...,5.000000,2.000000,4.000000,4.000000,4.000000,2.250000,3.000000,3.000000,2.000000,4.000000
max,9.000000,5.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [68]:
df.head(5)

,geschlecht,alter,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
0,weiblich,2004,Baden-Württemberg,3,5,2,2,1,1,1,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
1,maennlich,2004,Baden-Württemberg,3,3,2,2,1,1,2,...,5,2,4,5,4,2,1,1,3,4
2,weiblich,2002,Bayern,1,3,3,3,2,2,1,...,3,2,1,4,5,1,3,1,1,3
3,unbekannt,keine Angabe,keine Angabe,-99,2,3,3,1,1,3,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
4,maennlich,2005,Baden-Württemberg,3,3,2,2,1,2,2,...,4,1,3,2,3,2,3,3,1,1

In [69]:
df['beruf'] = df['beruf'].replace(-99, 10)

In [70]:
mapping = {
    1: "Angestellte / Angestellter",
    2: "Selbständige / Selbstständiger",
    3: "Studentin / Student",
    4: "Schülerin / Schüler",
    5: "Beamtin / Beamter",
    6: "Rentnerin / Rentner",
    7: "Hausfrau / Hausmann",
    8: "ohne Beschäftigung",
    9: "in Ausbildung/im Freiwilligendienst",
    10: "keine Angabe"
}

df['beruf'] = df['beruf'].map(mapping)

In [71]:
df['beruf'].value_counts()

Studentin / Student                    249
Angestellte / Angestellter             168
keine Angabe                            52
Schülerin / Schüler                     27
Beamtin / Beamter                       12
Selbständige / Selbstständiger          12
in Ausbildung/im Freiwilligendienst     10
ohne Beschäftigung                       5
Hausfrau / Hausmann                      1
Name: beruf, dtype: int64

In [72]:
df.head(5)

,geschlecht,alter,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
0,weiblich,2004,Baden-Württemberg,Studentin / Student,5,2,2,1,1,1,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
1,maennlich,2004,Baden-Württemberg,Studentin / Student,3,2,2,1,1,2,...,5,2,4,5,4,2,1,1,3,4
2,weiblich,2002,Bayern,Angestellte / Angestellter,3,3,3,2,2,1,...,3,2,1,4,5,1,3,1,1,3
3,unbekannt,keine Angabe,keine Angabe,keine Angabe,2,3,3,1,1,3,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
4,maennlich,2005,Baden-Württemberg,Studentin / Student,3,2,2,1,2,2,...,4,1,3,2,3,2,3,3,1,1

In [73]:
mapping = {
    1: "täglich",
    2: "mehrmals pro Woche",
    3: "mehrmals im Monat",
    4: "einmal pro Monat",
    5: "seltener als einmal pro Monat"
}

df['konsumhaeufigkeit'] = df['konsumhaeufigkeit'].map(mapping)

In [74]:
df['konsumhaeufigkeit'].value_counts()

mehrmals im Monat                238
mehrmals pro Woche               133
einmal pro Monat                  78
seltener als einmal pro Monat     67
täglich                           20
Name: konsumhaeufigkeit, dtype: int64

In [79]:
df.head(5)

,geschlecht,alter,bundesland,beruf,konsumhaeufigkeit,situation_freunde_familie,situation_party,situation_zuhause_essen,situation_zuhause_entspannung,situation_oeffentliche_veranstaltungen,...,praef_bier_alkohol,geschmack_rauchig,geschmack_hopfig,geschmack_suesslich_malzig,geschmack_fruchtig,geschmack_kraeuter,geschmack_gewuerze,geschmack_bitter,geschmack_saeuerlich,geschmack_zitrus
0,weiblich,2004,Baden-Württemberg,Studentin / Student,seltener als einmal pro Monat,2,2,1,1,1,...,4,2,3,3,3,2,2,2,2,3
1,maennlich,2004,Baden-Württemberg,Studentin / Student,mehrmals im Monat,2,2,1,1,2,...,5,2,4,5,4,2,1,1,3,4
2,weiblich,2002,Bayern,Angestellte / Angestellter,mehrmals im Monat,3,3,2,2,1,...,3,2,1,4,5,1,3,1,1,3
3,unbekannt,keine Angabe,keine Angabe,keine Angabe,mehrmals pro Woche,3,3,1,1,3,...,4,2,3,3,3,2,2,2,2,3
4,maennlich,2005,Baden-Württemberg,Studentin / Student,mehrmals im Monat,2,2,1,2,2,...,4,1,3,2,3,2,3,3,1,1

In [77]:
for col in df.select_dtypes(include='number').columns:
    median = df.loc[df[col] != -99, col].median()
    df[col] = df[col].replace(-99, median)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 60 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   geschlecht                              536 non-null    object
 1   alter                                   536 non-null    object
 2   bundesland                              536 non-null    object
 3   beruf                                   536 non-null    object
 4   konsumhaeufigkeit                       536 non-null    object
 5   situation_freunde_familie               536 non-null    int64
 6   situation_party                         536 non-null    int64
 7   situation_zuhause_essen                 536 non-null    int64
 8   situation_zuhause_entspannung           536 non-null    int64
 9   situation_oeffentliche_veranstaltungen  536 non-null    int64
 10  situation_gastro                        536 non-null    int64
 11  situation_urlaub                        536 non-null    int64
 12  involvement_interesse                   536 non-null    int64
 13  involvement_rolle                       536 non-null    int64
 14  involvement_spass                       536 non-null    int64
 15  involvement_wichtigkeit                 536 non-null    int64
 16  involvement_vorteilhaft                 536 non-null    int64
 17  involvement_unverzichtbar               536 non-null    int64
 18  gesundheit_wichtig                      536 non-null    int64
 19  umweltfreundlich_wichtig                536 non-null    int64
 20  neue_produkte_probie                    536 non-null    int64
 21  bio_mehrpreis_bereit                    536 non-null    int64
 22  tierfrei_wichtig                        536 non-null    int64
 23  alkoholverzicht_wichtig                 536 non-null    int64
 24  einfluss_geschmack                      536 non-null    int64
 25  einfluss_geruch                         536 non-null    int64
 26  einfluss_preis                          536 non-null    int64
 27  einfluss_markenbekanntheit              536 non-null    int64
 28  einfluss_nachhaltigkeit                 536 non-null    int64
 29  einfluss_herkunft                       536 non-null    int64
 30  einfluss_verpackungsdesign              536 non-null    int64
 31  einfluss_verpackungsform                536 non-null    int64
 32  einfluss_aktionsangebote                536 non-null    int64
 33  einfluss_alkoholgehalt                  536 non-null    int64
 34  einfluss_empfehlung                     536 non-null    int64
 35  einfluss_verfuegbarkeit                 536 non-null    int64
 36  praef_sorte_alkoholfrei                 536 non-null    int64
 37  praef_sorte_weizen                      536 non-null    int64
 38  praef_sorte_koelsch                     536 non-null    int64
 39  praef_sorte_altbier                     536 non-null    int64
 40  praef_sorte_pale_ale                    536 non-null    int64
 41  praef_sorte_stout                       536 non-null    int64
 42  praef_sorte_maerzen_export              536 non-null    int64
 43  praef_sorte_radler                      536 non-null    int64
 44  praef_sorte_pils                        536 non-null    int64
 45  praef_sorte_bock_schwarzrauchbier       536 non-null    int64
 46  praef_sorte_helles_lager                536 non-null    int64
 47  praef_sorte_craft_beer                  536 non-null    int64
 48  praef_alkoholfrei_0                     536 non-null    int64
 49  praef_alkoholfrei_0_5                   536 non-null    int64
 50  praef_bier_alkohol                      536 non-null    int64
 51  geschmack_rauchig                       536 non-null    int64
 52  geschmack_hopfig                        536 non-null    int64
 53  geschmack_suesslich_malzig              536 non-null    int64
 54  geschmack_fruchtig                      536 non-null    int64
 55  geschmack_kraeuter                      536 non-null    int64
 56  geschmack_gewuerze                      536 non-null    int64
 57  geschmack_bitter                        536 non-null    int64
 58  geschmack_saeuerlich                    536 non-null    int64
 59  geschmack_zitrus                        536 non-null    int64
dtypes: int64(55), object(5)
memory usage: 251.4+ KB

In [80]:
df.to_csv("../../data/data_for_CTGAN/CTGAN_basedata.csv", index=False)